# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [4]:
import numpy as np

# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Replace all the elements in the third column with 1
array[:, 2] = 1
print("Modified array:")
print(array)

Original array:
[[20  7  7  3 14]
 [14  7  2 18  5]
 [ 1  6 10  9 13]
 [ 4 12  6 16  1]
 [ 7  6 10 14 20]]
Modified array:
[[20  7  1  3 14]
 [14  7  1 18  5]
 [ 1  6  1  9 13]
 [ 4 12  1 16  1]
 [ 7  6  1 14 20]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [6]:
# Create a NumPy array of shape (4, 4) with values from 1 to 16
array = np.arange(1, 17).reshape((4, 4))
print("Original array:")
print(array)

# Replace the diagonal elements with 0
np.fill_diagonal(array, 0)
print("Modified array:")
print(array)

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Modified array:
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [7]:
# Create a NumPy array of shape (6, 6) with values from 1 to 36
array = np.arange(1, 37).reshape((6, 6))
print("Original array:")
print(array)

# Extract the sub-array
sub_array = array[2:5, 1:4]
print("Sub-array:")
print(sub_array)

Original array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Sub-array:
[[14 15 16]
 [20 21 22]
 [26 27 28]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [8]:
# Create a NumPy array of shape (5, 5) with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Extract the elements on the border
border_elements = np.concatenate((array[0, :], array[-1, :], array[1:-1, 0], array[1:-1, -1]))
print("Border elements:")
print(border_elements)

Original array:
[[ 6 18 12 17  7]
 [ 2  9 11 18  1]
 [20  7  9  5 10]
 [12  2 15 20 14]
 [18  2 17 13 13]]
Border elements:
[ 6 18 12 17  7 18  2 17 13 13  2 20 12  1 10 14]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [9]:
# Create two NumPy arrays of shape (3, 4) filled with random integers
array1 = np.random.randint(1, 11, size=(3, 4))
array2 = np.random.randint(1, 11, size=(3, 4))
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)

# Perform element-wise operations
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print("Element-wise addition:")
print(addition)
print("Element-wise subtraction:")
print(subtraction)
print("Element-wise multiplication:")
print(multiplication)
print("Element-wise division:")
print(division)

Array 1:
[[ 5  9 10  3]
 [ 7  6  1 10]
 [ 1  4  9  9]]
Array 2:
[[ 4 10  2  3]
 [ 1  8  2  9]
 [ 7  1  3  9]]
Element-wise addition:
[[ 9 19 12  6]
 [ 8 14  3 19]
 [ 8  5 12 18]]
Element-wise subtraction:
[[ 1 -1  8  0]
 [ 6 -2 -1  1]
 [-6  3  6  0]]
Element-wise multiplication:
[[20 90 20  9]
 [ 7 48  2 90]
 [ 7  4 27 81]]
Element-wise division:
[[1.25       0.9        5.         1.        ]
 [7.         0.75       0.5        1.11111111]
 [0.14285714 4.         3.         1.        ]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [10]:
# Create a NumPy array of shape (4, 4) with values from 1 to 16
array = np.arange(1, 17).reshape((4, 4))
print("Original array:")
print(array)

# Compute the row-wise and column-wise sum
row_sum = np.sum(array, axis=1)
column_sum = np.sum(array, axis=0)

print("Row-wise sum:")
print(row_sum)
print("Column-wise sum:")
print(column_sum)

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row-wise sum:
[10 26 42 58]
Column-wise sum:
[28 32 36 40]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [11]:
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Compute the statistical values
mean = np.mean(array)
median = np.median(array)
std_dev = np.std(array)
variance = np.var(array)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)
print("Variance:", variance)

Original array:
[[17  9  2  4  1]
 [ 5 11 11 16  6]
 [ 5 12 16 11 10]
 [15  1 10  8  9]
 [15 19  1  1 12]]
Mean: 9.08
Median: 10.0
Standard Deviation: 5.43264208281753
Variance: 29.513599999999997


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [12]:
# Create a NumPy array of shape (3, 3) with values from 1 to 9
array = np.arange(1, 10).reshape((3, 3))
print("Original array:")
print(array)

# Normalize the array
mean = np.mean(array)
std_dev = np.std(array)
normalized_array = (array - mean) / std_dev

print("Normalized array:")
print(normalized_array)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized array:
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [13]:
# Create a NumPy array of shape (3, 3) filled with random integers
array = np.random.randint(1, 11, size=(3, 3))
row_array = np.random.randint(1, 11, size=(3,))
print("Original array:")
print(array)
print("1D array:")
print(row_array)

# Add the 1D array to each row of the 2D array using broadcasting
result = array + row_array
print("Resulting array:")
print(result)

Original array:
[[ 3  8  4]
 [10  9  1]
 [ 5 10  6]]
1D array:
[ 5 10  5]
Resulting array:
[[ 8 18  9]
 [15 19  6]
 [10 20 11]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [14]:
# Create a NumPy array of shape (4, 4) filled with random integers
array = np.random.randint(1, 11, size=(4, 4))
column_array = np.random.randint(1, 11, size=(4,))
print("Original array:")
print(array)
print("1D array:")
print(column_array)

# Subtract the 1D array from each column of the 2D array using broadcasting
result = array - column_array[:, np.newaxis]
print("Resulting array:")
print(result)

Original array:
[[ 3  4  9  2]
 [ 2  3  9  9]
 [ 8 10  8  1]
 [ 3  7  2  9]]
1D array:
[5 7 1 8]
Resulting array:
[[-2 -1  4 -3]
 [-5 -4  2  2]
 [ 7  9  7  0]
 [-5 -1 -6  1]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [15]:
# Create a NumPy array of shape (3, 3) representing a matrix
matrix = np.random.randint(1, 11, size=(3, 3))
print("Original matrix:")
print(matrix)

# Compute the determinant
determinant = np.linalg.det(matrix)
print("Determinant:", determinant)

# Compute the inverse
inverse = np.linalg.inv(matrix)
print("Inverse:")
print(inverse)

# Compute the eigenvalues
eigenvalues = np.linalg.eigvals(matrix)
print("Eigenvalues:", eigenvalues)

Original matrix:
[[5 6 7]
 [9 3 2]
 [4 7 8]]
Determinant: 23.00000000000006
Inverse:
[[ 0.43478261  0.04347826 -0.39130435]
 [-2.7826087   0.52173913  2.30434783]
 [ 2.2173913  -0.47826087 -1.69565217]]
Eigenvalues: [17.07452676+0.j         -0.53726338+1.02877788j -0.53726338-1.02877788j]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [16]:
# Create two NumPy arrays of shape (2, 3) and (3, 2)
array1 = np.random.randint(1, 11, size=(2, 3))
array2 = np.random.randint(1, 11, size=(3, 2))
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)

# Perform matrix multiplication
result = np.dot(array1, array2)
print("Matrix multiplication result:")
print(result)

Array 1:
[[5 2 9]
 [3 9 5]]
Array 2:
[[4 4]
 [2 3]
 [6 1]]
Matrix multiplication result:
[[78 35]
 [60 44]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [17]:
# Create a NumPy array of shape (3, 3) with values from 1 to 9
array = np.arange(1, 10).reshape((3, 3))
print("Original array:")
print(array)

# Reshape the array to shape (1, 9)
reshaped_array_1 = array.reshape((1, 9))
print("Reshaped array (1, 9):")
print(reshaped_array_1)

# Reshape the array to shape (9, 1)
reshaped_array_2 = reshaped_array_1.reshape((9, 1))
print("Reshaped array (9, 1):")
print(reshaped_array_2)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshaped array (1, 9):
[[1 2 3 4 5 6 7 8 9]]
Reshaped array (9, 1):
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [19]:
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Flatten the array
flattened_array = array.flatten()
print("Flattened array:")
print(flattened_array)

# Reshape the array back to (5, 5)
reshaped_array = flattened_array.reshape((5, 5))
print("Reshaped array:")
print(reshaped_array)

Original array:
[[ 1 10  1  1 14]
 [18 11  1 19 16]
 [12 10 12 20  5]
 [ 5  3 19  5  1]
 [ 4  9 14 10 10]]
Flattened array:
[ 1 10  1  1 14 18 11  1 19 16 12 10 12 20  5  5  3 19  5  1  4  9 14 10
 10]
Reshaped array:
[[ 1 10  1  1 14]
 [18 11  1 19 16]
 [12 10 12 20  5]
 [ 5  3 19  5  1]
 [ 4  9 14 10 10]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [ ]:
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Use fancy indexing to extract the elements at the corners of the array
corners = array[[0, 0, -1, -1], [0, -1, 0, -1]]
# (row 0, column 0)    -> top-left
# (row 0, column -1)   -> top-right
# (row -1, column 0)   -> bottom-left
# (row -1, column -1)  -> bottom-right
print("Corner elements:")
print(corners)

Original array:
[[ 6 19 12 10 14]
 [11  4  8  5 10]
 [ 8 12 19  3  7]
 [ 2  1 16  4 12]
 [ 9 16 16 15 20]]
Corner elements:
[ 6 14  9 20]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [22]:
# Create a NumPy array of shape (4, 4) filled with random integers
array = np.random.randint(1, 21, size=(4, 4))
print("Original array:")
print(array)

# Use boolean indexing to set all elements greater than 10 to 10
array[array > 10] = 10
print("Modified array:")
print(array)

Original array:
[[11 14 10  4]
 [ 9 15  6 18]
 [ 1 14 17  2]
 [18  2 11 11]]
Modified array:
[[10 10 10  4]
 [ 9 10  6 10]
 [ 1 10 10  2]
 [10  2 10 10]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [23]:
# Create a structured array with fields 'name', 'age', and 'weight'
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print("Original array:")
print(data)

# Sort the array by age
sorted_data = np.sort(data, order='age')
print("Sorted array by age:")
print(sorted_data)

Original array:
[('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]
Sorted array by age:
[('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

For two points:

```text
Point A = (x1, y1)
Point B = (x2, y2)
```

the Euclidean distance is:

$$
d = \sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}
$$

In Python:

```python
distance = np.sqrt((x2 - x1) ** 2 + (y2 - y1) ** 2)
```

For example, between `(1, 2)` and `(3, 4)`:

$$
d = \sqrt{(3-1)^2 + (4-2)^2} = \sqrt{8} \approx 2.83
$$

In [ ]:
# Create a structured array with fields 'x' and 'y'
data_type = [('x', 'i4'), ('y', 'i4')]
data = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)
print("Original array:")
print(data)

# Compute the Euclidean distance between each pair of points
distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print("Euclidean distances:")
print(distances)

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

In [24]:
import numpy.ma as ma
# Imports NumPy’s masked-array tools.

# Create a masked array of shape (4, 4) with random integers
array = np.random.randint(1, 21, size=(4, 4))

masked_array = ma.masked_greater(array, 10)
# Masks, or hides, every value greater than 10. Values from 1 to 10 remain visible.

print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Compute the sum of the unmasked elements
sum_unmasked = masked_array.sum()
print("Sum of unmasked elements:", sum_unmasked)

Original array:
[[ 9  7  5 20]
 [ 2  1 12 15]
 [16 19  7  4]
 [ 8  3  6 15]]
Masked array:
[[9 7 5 --]
 [2 1 -- --]
 [-- -- 7 4]
 [8 3 6 --]]
Sum of unmasked elements: 52


2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [27]:
# Create a masked array of shape (3, 3) with random integers
array = np.random.randint(1, 21, size=(3, 3))
masked_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Replace the masked elements with the mean of the unmasked elements
mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print("Modified masked array:")
print(masked_array)

Original array:
[[ 4 15 12]
 [ 3  3  1]
 [ 9 14  4]]
Masked array:
[[-- 15 12]
 [3 -- 1]
 [9 14 --]]
Modified masked array:
[[ 9 15 12]
 [ 3  9  1]
 [ 9 14  9]]



```python
masked_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))
```

Creates a masked version of `array`.

- `np.eye(3, dtype=bool)` creates this mask:

```python
[[ True, False, False],
 [ False, True, False],
 [ False, False, True]]
```

`True` means “hide this value,” so the diagonal values are hidden.

```python
print("Original array:")
print(array)
```

Prints the original array, including every value.

```python
print("Masked array:")
print(masked_array)
```

Prints the array with diagonal values hidden, usually shown as `--`.

```python
# Replace the masked elements with the mean of the unmasked elements
```

This comment explains the next step.

```python
mean_unmasked = masked_array.mean()
```

Calculates the average of the visible values only. The hidden diagonal values are ignored.

```python
masked_array = masked_array.filled(mean_unmasked)
```

Replaces the hidden diagonal values with the calculated average.

```python
print("Modified masked array:")
print(masked_array)
```

Prints the final array, where the diagonal contains the average of the unmasked values.
