# NumPy — fast number boxes

> **Explain it like I am five:** A Python list is a mixed toy box. A NumPy array is a neat egg tray: every slot has a position, the same kind of value fits efficiently, and we can change a whole row at once.

NumPy is the numerical foundation used by Pandas, scientific Python, and much of machine learning. This lesson keeps every original example, explains what it does, and adds the concepts normally needed next.

## Learning goals

- create 1D and 2D arrays;
- read `shape`, `ndim`, `size`, and `dtype`;
- index, slice, reshape, and combine arrays;
- use vectorization, broadcasting, masks, and statistics;
- understand views, copies, axes, random generators, and basic linear algebra.


## 0. Setup

Install once only if the import fails:

```python
%pip install numpy
```

`%pip` is preferred inside Jupyter because it installs into the active notebook environment. The original notebook used `!pip install numpy`; both demonstrate the same setup idea.


In [1]:
import numpy as np

print("NumPy version:", np.__version__)


NumPy version: 2.4.6


## 1. Create a one-dimensional array

An array has **values**, a **shape**, and a **data type**. Shape `(5,)` means one axis containing five elements.


In [2]:
## create array using numpy
## create a 1D array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


## 2. Dimensions and reshape

Compare these shapes carefully:

- `(5,)` — a 1D array;
- `(1, 5)` — a 2D table with one row and five columns;
- `(5, 1)` — a 2D table with five rows and one column.

`reshape` changes the arrangement, not the values. The number of slots must stay equal.


In [3]:
## 1 d array
arr2=np.array([1,2,3,4,5])
print(arr2.reshape(1,5))  ## 1 row and 5 columns
print("original shape:", arr2.shape)


[[1 2 3 4 5]]
original shape: (5,)


In [4]:
arr2=np.array([[1,2,3,4,5]])
print(arr2)
print("shape:", arr2.shape)


[[1 2 3 4 5]]
shape: (1, 5)


In [5]:
## 2d array
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)


[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [6]:
values = np.arange(1, 13)
print(values.reshape(3, 4))
print(values.reshape(2, -1))  # -1 asks NumPy to calculate this dimension.


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


## 3. Array-building helpers

- `arange(start, stop, step)` is like `range`, but returns an array.
- `zeros` and `ones` fill a requested shape.
- `full` fills with a chosen value.
- `eye` builds an identity matrix.
- `linspace(start, stop, count)` creates an exact number of evenly spaced values.


In [7]:
print(np.arange(0,10,2).reshape(5,1))


[[0]
 [2]
 [4]
 [6]
 [8]]


In [8]:
print(np.ones((3,4)))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
## identity matrix
print(np.eye(3))


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
print("zeros:\n", np.zeros((2, 3)))
print("full:\n", np.full((2, 3), 7))
print("linspace:", np.linspace(0, 1, 5))


zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
full:
 [[7 7 7]
 [7 7 7]]
linspace: [0.   0.25 0.5  0.75 1.  ]


## 4. Important array attributes

Think of an array as a labeled package:

- `shape`: package dimensions;
- `ndim`: number of axes;
- `size`: total item count;
- `dtype`: kind of values;
- `itemsize`: bytes used by one value.


In [11]:
## Attributes of Numpy Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)  # Output: (2, 3)
print("Number of dimensions:", arr.ndim)  # Output: 2
print("Size (number of elements):", arr.size)  # Output: 6
print("Data type:", arr.dtype)  # Platform and input dependent
print("Item size (in bytes):", arr.itemsize)  # Platform and dtype dependent


Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


## 5. Indexing and slicing

Python counts from zero. In `arr[row, column]`, the first number chooses a row and the second chooses a column. Slice stops are excluded.


In [12]:
## array slicing and Indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)


Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
print(arr[1:,1:3])


[[ 6  7]
 [10 11]]


In [14]:
print(arr[0][0])
print(arr[0:2,2:])


1
[[3 4]
 [7 8]]


In [15]:
print(arr[1:,2:])


[[ 7  8]
 [11 12]]


### Slices are often views

A slice may share memory with its parent. It is like a window looking into the same house: changing what you see through the window can change the house. Call `.copy()` when you need an independent array.


In [16]:
original = np.array([10, 20, 30, 40])
view = original[1:3]
independent = original[1:3].copy()

view[0] = 999
independent[1] = -1
print("original:", original)
print("view:", view)
print("independent copy:", independent)


original: [ 10 999  30  40]
view: [999  30]
independent copy: [20 -1]


## 6. Modify array elements

Assignment can target one cell, a slice, or every location selected by a mask.


In [17]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr[0,0]=100
print(arr)


[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [18]:
arr[1:]=100
print(arr)


[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


## 7. Vectorized operations

Vectorization asks NumPy's compiled loops to operate on whole arrays. It is shorter and usually faster than a Python loop.

Arithmetic between equal-shaped arrays happens **element by element**. Matrix multiplication is different and uses `@`.


In [19]:
### Numpy Vectorized Operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

### Element Wise addition
print("Addition:", arr1+arr2)

## Element Wise Substraction
print("Substraction:", arr1-arr2)

# Element-wise multiplication
print("Multiplication:", arr1 * arr2)

# Element-wise division
print("Division:", arr1 / arr2)


Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


## 8. Broadcasting

Broadcasting is NumPy pretending a smaller array is repeated to match a larger one—without actually copying it many times.

Shapes align from the right. Each aligned dimension must be equal or one of them must be `1`.


In [20]:
prices = np.array([[100, 200, 300], [150, 250, 350]])
discount_by_column = np.array([10, 20, 30])
print(prices - discount_by_column)

row_bonus = np.array([[5], [50]])
print(prices + row_bonus)


[[ 90 180 270]
 [140 230 320]]
[[105 205 305]
 [200 300 400]]


`prices` is `(2, 3)`. A `(3,)` array matches the three columns; a `(2, 1)` array has one value per row and broadcasts across columns.


## 9. Universal functions (ufuncs)

A ufunc applies a mathematical operation element by element. Logarithms require positive inputs, and square roots of negative real numbers produce invalid values.


In [21]:
## Universal Function
arr=np.array([2,3,4,5,6])
## square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine
print(np.sin(arr))

## natural log
print(np.log(arr))


[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


## 10. Aggregations and axes

An **axis is the direction NumPy collapses**:

- `axis=0` collapses rows and gives one result per column;
- `axis=1` collapses columns and gives one result per row;
- no axis gives one result for the whole array.


In [22]:
scores = np.array([[80, 90, 70], [60, 75, 95]])
print("whole mean:", scores.mean())
print("column means (axis=0):", scores.mean(axis=0))
print("row means (axis=1):", scores.mean(axis=1))
print("row sums:", scores.sum(axis=1))


whole mean: 78.33333333333333
column means (axis=0): [70.  82.5 82.5]
row means (axis=1): [80.         76.66666667]
row sums: [240 230]


## 11. Statistics and standardization

The original “normalization” example actually performs **standardization (z-scores)**: subtract the mean, then divide by the standard deviation. The result has mean near 0 and standard deviation near 1.


In [23]:
### statistical concepts--Normalization
## to have a mean of 0 and standard deviation of 1
data = np.array([1, 2, 3, 4, 5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)
print("check mean/std:", normalized_data.mean(), normalized_data.std())


Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
check mean/std: 0.0 0.9999999999999999


In [24]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)


Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


### Standardization vs. min-max scaling

- **Standardization:** `(x - mean) / std` centers and scales spread.
- **Min-max scaling:** `(x - min) / (max - min)` maps values to 0–1.

Guard against a zero denominator when every value is equal.


In [25]:
values = np.array([10, 20, 30, 40], dtype=float)
value_range = values.max() - values.min()
min_max = (values - values.min()) / value_range if value_range else np.zeros_like(values)
print(min_max)


[0.         0.33333333 0.66666667 1.        ]


## 12. Boolean masks and logical operations

A condition creates a same-shaped array of `True`/`False` values. Use `&`, `|`, and `~` for element-wise AND, OR, and NOT. Put each comparison in parentheses.


In [26]:
## Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

print(data[(data>=5) & (data<=8)])


[5 6 7 8]


In [27]:
temperatures = np.array([18, 25, 31, 42, 27])
labels = np.where(temperatures >= 30, "hot", "comfortable")
capped = np.clip(temperatures, 20, 35)

print(labels)
print(capped)


['comfortable' 'comfortable' 'hot' 'hot' 'comfortable']
[20 25 31 35 27]


## 13. Missing numeric values

NumPy represents a missing floating-point value with `np.nan`. Ordinary mean becomes `nan`; nan-aware functions skip missing entries.


In [28]:
measurements = np.array([10.0, np.nan, 14.0, 16.0])
print("ordinary mean:", np.mean(measurements))
print("nan-aware mean:", np.nanmean(measurements))
print("missing mask:", np.isnan(measurements))


ordinary mean: nan
nan-aware mean: 13.333333333333334
missing mask: [False  True False False]


## 14. Deterministic random numbers

Use `np.random.default_rng(seed)` for modern random-number generation. The seed is a recipe number: the same seed reproduces the same practice data.


In [29]:
rng = np.random.default_rng(42)
random_scores = rng.integers(1, 101, size=(3, 4))
print(random_scores)


[[ 9 78 66 44]
 [44 86  9 70]
 [21 10 53 98]]


## 15. Combining arrays

- `concatenate` joins along an existing axis;
- `vstack` stacks rows;
- `hstack` stacks columns.


In [30]:
top = np.array([[1, 2], [3, 4]])
bottom = np.array([[5, 6]])

print("vertical:\n", np.vstack([top, bottom]))
print("horizontal:\n", np.hstack([top, top]))
print("flat join:", np.concatenate([top.ravel(), bottom.ravel()]))


vertical:
 [[1 2]
 [3 4]
 [5 6]]
horizontal:
 [[1 2 1 2]
 [3 4 3 4]]
flat join: [1 2 3 4 5 6]


## 16. Element-wise multiplication vs. matrix multiplication

`a * b` multiplies matching cells. `a @ b` performs the row-by-column rule from linear algebra. For `a @ b`, the inside dimensions must match.


In [31]:
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

print("element-wise:\n", matrix_a * matrix_b)
print("matrix product:\n", matrix_a @ matrix_b)
print("transpose:\n", matrix_a.T)


element-wise:
 [[ 5 12]
 [21 32]]
matrix product:
 [[19 22]
 [43 50]]
transpose:
 [[1 3]
 [2 4]]


## 17. Common mistakes

- **Shape mismatch:** inspect `.shape` before arithmetic or matrix multiplication.
- **Confusing a view with a copy:** use `.copy()` before isolated edits.
- **Using `and`/`or` with arrays:** use `&`/`|` and parentheses.
- **Dividing by zero during scaling:** check the standard deviation or range.
- **Assuming integer arrays can store decimals:** create or convert to a float dtype.
- **Expecting `*` to mean matrix multiplication:** use `@`.
- **Using `np.random` global state for new code:** prefer `default_rng`.


## 18. Mini practice

1. Create numbers 1–24 and reshape them to `(4, 6)`.
2. Select values divisible by 3.
3. Find each row's maximum using an axis.
4. Add `[10, 20, 30]` to every row of a `(2, 3)` array.


In [32]:
practice = np.arange(1, 25).reshape(4, 6)
print(practice)
print("divisible by 3:", practice[practice % 3 == 0])
print("row maximums:", practice.max(axis=1))

small = np.array([[1, 2, 3], [4, 5, 6]])
print(small + np.array([10, 20, 30]))


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
divisible by 3: [ 3  6  9 12 15 18 21 24]
row maximums: [ 6 12 18 24]
[[11 22 33]
 [14 25 36]]


## Easy revision cheat sheet

| Goal | NumPy pattern |
|---|---|
| Create | `np.array([...])` |
| Integer sequence | `np.arange(start, stop, step)` |
| Even spacing | `np.linspace(start, stop, count)` |
| Inspect | `a.shape`, `a.ndim`, `a.size`, `a.dtype` |
| Reshape | `a.reshape(rows, cols)` |
| Select cell | `a[row, column]` |
| Select block | `a[r1:r2, c1:c2]` |
| Independent slice | `a[...].copy()` |
| Filter | `a[(a >= low) & (a <= high)]` |
| Choose by condition | `np.where(condition, yes, no)` |
| Limit range | `np.clip(a, low, high)` |
| Column result | `a.mean(axis=0)` |
| Row result | `a.mean(axis=1)` |
| Matrix product | `a @ b` |
| Reproducible random | `np.random.default_rng(seed)` |
| Missing-aware mean | `np.nanmean(a)` |

**Memory trick:** Shape tells you how many shelves and slots the array has; axis tells NumPy which direction to fold when making a summary.
